  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: magi_development
  pool: 5
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: magi_test
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: magi_production
  pool: 5
  username: root
  password:
  host: localhost
